In [1]:
import numpy as np
import pandas as pd

In [3]:
headers = ['customerNumber', 'customerName', 'contactLastName', 'contactFirstName', 
           'phone', 'addressLine1', 'addressLine2', 'city', 'state', 'postalCode', 
           'country', 'salesRepEmployeeNumber', 'creditLimit']
data = pd.read_csv('./Customers.csv', names=headers, encoding='iso-8859-1')

In [10]:
data.head(10)

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",NaN,Nantes,NaN,44000,France,1370.0,21000
1,112,Signal Gift Stores,King,Sue,7025551838,8489 Strong St.,NaN,Las Vegas,NV,83030,USA,1166.0,71800
2,114,Australian Collectors Co.,Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,67 rue des Cinquante Otages,NaN,Nantes,NaN,44000,France,1370.0,118200
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,1504.0,81700
5,124,Mini Gifts Distributors Ltd.,Nelson,Valarie,4155551450,5677 Strong St.,NaN,San Rafael,CA,97562,USA,1165.0,210500
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,NaN,Warszawa,NaN,01-012,Poland,NaN,0
7,128,Blauer See Auto Co.,Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,1504.0,59700
8,129,Mini Wheels Co.,Murphy,Julie,6505555787,5557 North Pendale Street,NaN,San Francisco,CA,94217,USA,1165.0,64600
9,131,Land of Toys Inc.,Yu,Kwai,2125557818,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,1323.0,114900

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerNumber          122 non-null    int64
 1   customerName            122 non-null    object
 2   contactLastName         122 non-null    object
 3   contactFirstName        122 non-null    object
 4   phone                   122 non-null    object
 5   addressLine1            122 non-null    object
 6   addressLine2            13 non-null     object
 7   city                    122 non-null    object
 8   state                   48 non-null     object
 9   postalCode              115 non-null    object
 10  country                 122 non-null    object
 11  salesRepEmployeeNumber  100 non-null    float64
 12  creditLimit             122 non-null    int64
dtypes: float64(1), int64(2), object(10)
memory usage: 12.5+ KB

In [15]:
# data[data.isna().any(axis=1)] # get all row with null values
data[pd.isnull(data.salesRepEmployeeNumber)] # get all row with null salesRepEmployeeNumber

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,NaN,Warszawa,NaN,01-012,Poland,NaN,0
21,169,Porto Imports Co.,de Castro,Isabel,(1) 356-5555,Estrada da saúde n. 58,NaN,Lisboa,NaN,1756,Portugal,NaN,0
36,206,"Asian Shopping Network, Co",Walker,Brydey,+612 9411 1555,Penthouse Level Suntec Tower Three 8 Temasek,NaN,Singapore,NaN,38988,Singapore,NaN,0
41,223,Natürlich Autos,Kloss,Horst,0372-555188,Taucherstraße 10,NaN,Cunewalde,NaN,1307,Germany,NaN,0
44,237,ANG Resellers,Camino,Alejandra,(91) 745 6555,Gran Vía 1,NaN,Madrid,NaN,28001,Spain,NaN,0
48,247,Messner Shopping Network,Messner,Renate,069-0555984,Magazinweg 7,NaN,Frankfurt,NaN,60528,Germany,NaN,0
54,273,Franken Gifts Co,Franken,Peter,089-0877555,Berliner Platz 43,NaN,München,NaN,80805,Germany,NaN,0
59,293,BG&E Collectables,Pon,Ed,+41 26 425 50 01,Rte des Arsenaux 41,NaN,Fribourg,NaN,1700,Switzerland,NaN,0
62,303,Schuyler Imports,Schuyler,Bradley,+31 20 491 9555,Kingsfordweg 151,NaN,Amsterdam,NaN,1043 GR,Netherlands,NaN,0
63,307,Der Hund Imports,Anders,Maria,030-0074555,Obere Str. 57,NaN,Berlin,NaN,12209,Germany,NaN,0
74,335,Cramer Spezialitäten Ltd,Cramer,Philip,0555-09555,Maubelstr. 90,NaN,Brandenburg,NaN,14776,Germany,NaN,0
78,348,Asian Treasures Inc.,McKenna,Patricia,2967 555,8 Johnstown Road,NaN,Cork,Co. Cork,NaN,Ireland,NaN,0
81,356,SAR Distributors Co,Kuger,Armand,+27 21 550 3555,Century City-Montague Gardens PO Box 37177,NaN,Chempet,NaN,7442,South Africa,NaN,0
83,361,Kommission Auto,Josephs,Karin,0251-555259,Luisenstr. 48,NaN,Münster,NaN,44087,Germany,NaN,0
86,369,Lisboa Souveniers Inc,Rodriguez,Lino,(1) 354-2555,Jardim das rosas n. 32,NaN,Lisboa,NaN,1675,Portugal,NaN,0
95,409,Stuttgart Collectable Exchange,Müller,Rita,0711-555361,Adenauerallee 900,NaN,Stuttgart,NaN,70563,Germany,NaN,0
99,443,Feuer Online Stores Inc,Feuer,Alexander,0342-555176,Heerstr. 22,NaN,Leipzig,NaN,4179,Germany,NaN,0
107,459,Warburg Exchange,Ottlieb,Sven,0241-039123,Walserweg 21,NaN,Aachen,NaN,52066,Germany,NaN,0
109,465,"Anton Designs, Ltd.",Anton,Carmen,+34 913 728555,c/ Gobelas 19-1 Urb. La Florida,NaN,Madrid,NaN,28023,Spain,NaN,0
113,477,Mit Vergnügen & Co.,Moos,Hanna,0621-08555,Forsterstr. 57,NaN,Mannheim,NaN,68306,Germany,NaN,0
114,480,Kremlin Collectables Co.,Semenov,Alexander,+7 812 293 0521,2 Pobedy Square,NaN,Saint Petersburg,NaN,196143,Russia,NaN,0
115,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,NaN,Herzlia,NaN,47625,Israel,NaN,0

In [17]:
data = data.fillna({'salesRepEmployeeNumber': ''})

In [29]:
data[pd.isnull(data.salesRepEmployeeNumber)]

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,NaN,Warszawa,NaN,01-012,Poland,NaN,0
21,169,Porto Imports Co.,de Castro,Isabel,(1) 356-5555,Estrada da saúde n. 58,NaN,Lisboa,NaN,1756,Portugal,NaN,0
36,206,"Asian Shopping Network, Co",Walker,Brydey,+612 9411 1555,Penthouse Level Suntec Tower Three 8 Temasek,NaN,Singapore,NaN,38988,Singapore,NaN,0
41,223,Natürlich Autos,Kloss,Horst,0372-555188,Taucherstraße 10,NaN,Cunewalde,NaN,1307,Germany,NaN,0
44,237,ANG Resellers,Camino,Alejandra,(91) 745 6555,Gran Vía 1,NaN,Madrid,NaN,28001,Spain,NaN,0
48,247,Messner Shopping Network,Messner,Renate,069-0555984,Magazinweg 7,NaN,Frankfurt,NaN,60528,Germany,NaN,0
54,273,Franken Gifts Co,Franken,Peter,089-0877555,Berliner Platz 43,NaN,München,NaN,80805,Germany,NaN,0
59,293,BG&E Collectables,Pon,Ed,+41 26 425 50 01,Rte des Arsenaux 41,NaN,Fribourg,NaN,1700,Switzerland,NaN,0
62,303,Schuyler Imports,Schuyler,Bradley,+31 20 491 9555,Kingsfordweg 151,NaN,Amsterdam,NaN,1043 GR,Netherlands,NaN,0
63,307,Der Hund Imports,Anders,Maria,030-0074555,Obere Str. 57,NaN,Berlin,NaN,12209,Germany,NaN,0
74,335,Cramer Spezialitäten Ltd,Cramer,Philip,0555-09555,Maubelstr. 90,NaN,Brandenburg,NaN,14776,Germany,NaN,0
78,348,Asian Treasures Inc.,McKenna,Patricia,2967 555,8 Johnstown Road,NaN,Cork,Co. Cork,NaN,Ireland,NaN,0
81,356,SAR Distributors Co,Kuger,Armand,+27 21 550 3555,Century City-Montague Gardens PO Box 37177,NaN,Chempet,NaN,7442,South Africa,NaN,0
83,361,Kommission Auto,Josephs,Karin,0251-555259,Luisenstr. 48,NaN,Münster,NaN,44087,Germany,NaN,0
86,369,Lisboa Souveniers Inc,Rodriguez,Lino,(1) 354-2555,Jardim das rosas n. 32,NaN,Lisboa,NaN,1675,Portugal,NaN,0
95,409,Stuttgart Collectable Exchange,Müller,Rita,0711-555361,Adenauerallee 900,NaN,Stuttgart,NaN,70563,Germany,NaN,0
99,443,Feuer Online Stores Inc,Feuer,Alexander,0342-555176,Heerstr. 22,NaN,Leipzig,NaN,4179,Germany,NaN,0
107,459,Warburg Exchange,Ottlieb,Sven,0241-039123,Walserweg 21,NaN,Aachen,NaN,52066,Germany,NaN,0
109,465,"Anton Designs, Ltd.",Anton,Carmen,+34 913 728555,c/ Gobelas 19-1 Urb. La Florida,NaN,Madrid,NaN,28023,Spain,NaN,0
113,477,Mit Vergnügen & Co.,Moos,Hanna,0621-08555,Forsterstr. 57,NaN,Mannheim,NaN,68306,Germany,NaN,0
114,480,Kremlin Collectables Co.,Semenov,Alexander,+7 812 293 0521,2 Pobedy Square,NaN,Saint Petersburg,NaN,196143,Russia,NaN,0
115,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,NaN,Herzlia,NaN,47625,Israel,NaN,0

In [28]:
data

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",NaN,Nantes,NaN,44000,France,1370.0,21000
1,112,Signal Gift Stores,King,Sue,7025551838,8489 Strong St.,NaN,Las Vegas,NV,83030,USA,1166.0,71800
2,114,Australian Collectors Co.,Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,67 rue des Cinquante Otages,NaN,Nantes,NaN,44000,France,1370.0,118200
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,1504.0,81700
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,486,Motor Mint Distributors Inc.,Hernandez,Rosa,2155559857,11328 Douglas Av.,NaN,Philadelphia,PA,71270,USA,1323.0,72600
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,NaN,Brisbane,CA,94217,USA,1165.0,60300
119,489,Double Decker Gift Stores Ltd,Hardy,Thomas,(171) 555-7555,120 Hanover Sq.,NaN,London,NaN,WA1 1DP,UK,1501.0,43300
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,NaN,Boston,MA,51003,USA,1188.0,85100
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',NaN,Auckland,NaN,NaN,New Zealand,1612.0,110000

In [26]:
data.salesRepEmployeeNumber = pd.to_numeric(data.salesRepEmployeeNumber, errors='coerce', downcast='unsigned')

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerNumber          122 non-null    int64
 1   customerName            122 non-null    object
 2   contactLastName         122 non-null    object
 3   contactFirstName        122 non-null    object
 4   phone                   122 non-null    object
 5   addressLine1            122 non-null    object
 6   addressLine2            13 non-null     object
 7   city                    122 non-null    object
 8   state                   48 non-null     object
 9   postalCode              115 non-null    object
 10  country                 122 non-null    object
 11  salesRepEmployeeNumber  100 non-null    float64
 12  creditLimit             122 non-null    int64
dtypes: float64(1), int64(2), object(10)
memory usage: 12.5+ KB

In [30]:
data.to_csv('salesrepfix.csv', header=False, index=False)